FROM caddy:2.11.3-builder-alpine@sha256:3eae6b351ecdb05da6d16e341261a457692d344a435764c5ece7a60cf03a23f3 AS caddy-builder

RUN xcaddy build v2.11.3 \
        --with github.com/caddy-dns/cloudflare@v0.2.1 \
        --with github.com/caddy-dns/digitalocean@04bde2867106aa1b44c2f9da41a285fa02e629c5 \
        --with github.com/mholt/caddy-l4@6faae83b167fda94e62b686be5cbeb9b3f8fe002 \
        --with github.com/go-jose/go-jose/v3@v3.0.5 \
        --with github.com/go-jose/go-jose/v4@v4.1.4 \
        --with google.golang.org/grpc@v1.80.0 \
        --with go.opentelemetry.io/otel@v1.43.0 \
        --with go.opentelemetry.io/otel/sdk@v1.43.0

FROM caddy:2.11.3-alpine@sha256:86deaf5e3d3408a6ccec08fbb79989783dd26e206ae10bcf78a801dc8c9ab794 AS runtime

RUN apk update && apk upgrade --no-cache && apk add --no-cache nss-tools bash curl

COPY --from=caddy-builder /usr/bin/caddy /usr/bin/caddy

COPY Caddyfile.ce /etc/caddy/Caddyfile